.dockerignore, Gemfile, Gemfile.lock, Guardfile, app/services/adapters/kubectl_adapter.rb, app/services/support/service_token_authoritative_source.rb, deploy/fb-service-token-cache-chart/templates/deployment.yaml, spec/services/adapters/kubectl_adapter_spec.rb, spec/services/support/service_token_authoritative_source_spec.rb
- This changes the underlying responsibility of service token cache to now become an application token cache. This enables all components to determine if messages from any other component is acceptable
- This checks platform base components first then service components in that order
- Also refactored out some class methods to use instance methods internally instead
=> Application token cache

Gemfile, Gemfile.lock, spec/spec_helper.rb
I've added a minimum code coverage at the current coverage level to ensure code coverage does not decrease. We can work towards 100% coverage in subsequent PRs.
Also added a nice formatter to clearly display coverage results:
=> Add minimum coverage and format output

DEPLOY.md, Makefile, deploy/fb-service-token-cache-chart/templates/deployment.yaml, package.json, scripts/circleci_deploy.sh, scripts/restart_platform_pods.sh
Instead of manually deleting pods (resulting in downtime), use kubernetes
built-in rolling deployments.  This requires a dynamic tag on the container
image that can be referred to by the Helm deployment.yaml file.
By simply using a tag like latest, that never changes, kubernetes won't pick up
that anything has changed and not deploy.
=> Rolling deployments

app/controllers/health_controller.rb, config/routes.rb, deploy/fb-service-token-cache-chart/templates/deployment.yaml, spec/requests/health_spec.rb
Even though we are doing rolling deploys, it seems that traffic is being served
to the pods before Rails has booted. So this is still resulting in downtime.
By exposing an endpoint for the readiness probe to test, we can ensure that the application
will be ready to serve traffic by the time it is registered with the load balancer.
=> Add Kubernetes readiness probe

app/controllers/service_token_v2_controller.rb, app/services/adapters/kubectl_adapter.rb, app/services/support/service_token_authoritative_source.rb, config/routes.rb, spec/controllers/service_token_v2_controller_spec.rb, spec/services/adapters/kubectl_adapter_spec.rb, spec/support/json_only_api.rb
- this implements another endpoint that now returns the public key of the service which can then be used to verify signatures
=> add public key endpoint

.circleci/config.yml
[Trello](https://trello.com/c/OP1n7Bve/181-formalise-docker-build-image-for-circleci)
Replace image from docker hub with aws ecr
=> Replace image from docker hub with aws ecr (in test)

.circleci/config.yml
After merging #94 it was discovered that this repo doesn't trigger the acceptance test within the workflow, so adding the acceptance tests to boost more reliable applications to test and production.
* Add CIRCLE TOKEN env to Cicle CI
* Create this PR.
=> Add acceptance test workflow to this repo

Dockerfile
This can give a boost to our bundle install (I see at you Nokogiri!). The no-cache option is deprecated so removing it.
=> Add 4 workers to bundle install to improve performance

app/services/public_key_service.rb, deploy/fb-service-token-cache-chart/templates/config_map.yaml, spec/controllers/service_token_v2_controller_spec.rb
We need to be able to rebuild the redis cluster without causing errors to our end users. We can set a maintenance mode in the runner but it will still request the public key from the service token cache for any request that it gets.
Setting the `IGNORE_CACHE` environment variable will force public key to be requested from where it is stored in the kubernetes cluster for every request.
The rebuilding of the redis cluster does not take too long and we will choose a time where there are lower numbers of users so it should not impact services heavily.
https://trello.com/c/fKay4n3y/575-show-maintenance-page-without-requiring-elasticache-connection
=> Add ability to ignore caching

deploy/fb-service-token-cache-chart/templates/config_map.yaml
This is to allow the redis cluster to be rebuilt
https://trello.com/c/wMjJI6BB/557-communicate-and-carry-out-elasticache-rebuilding
=> Enable ignoring of the cache

deploy/fb-service-token-cache-chart/templates/config_map.yaml
Once the redis cluster has been rebuilt we can go back to using it
https://trello.com/c/wMjJI6BB/557-communicate-and-carry-out-elasticache-rebuilding
=> Re-enable use of caching

.circleci/config.yml
We only want the acceptance tests to run if the spec tests have actually passed
=> Trigger acceptance tests after specs have passed

deploy/fb-service-token-cache-chart/templates/deployment.yaml
Kubernetes has been upgraded to 1.16. These changes are required for the resources to continue working.
Followed the guide here:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/apiversion-changes-k8s-1-16.html#resources-deployed-using-helm-charts
https://trello.com/c/w8d8G6RM/696-cloud-platform-kubernetes-update
=> Update kubernetes resources

.circleci/config.yml
Now that our deployment pipeline checks for whether a pod has been successfully restarted we can trigger the acceptance tests later.
=> Trigger acceptance tests after successful rollout restart

app/services/adapters/shell_adapter.rb, spec/services/adapters/shell_adapter_spec.rb
We do not want the Kubernetes token to be printed out in the errors that are sent to Sentry.
https://trello.com/c/LfLkccvb/963-redact-kubernetes-token-in-service-token-cache
=> Redact Kubernetes token from messages sent to Sentry

app/controllers/service_token_v3_controller.rb, app/services/adapters/kubectl_adapter.rb, app/services/public_key_service.rb, app/services/support/service_token_authoritative_source.rb, config/routes.rb, spec/controllers/service_token_v3_controller_spec.rb, spec/services/adapters/kubectl_adapter_spec.rb
We need to pass a namespace to the service token cache as we are expanding the use of JWT tokens to be cross namespace, not just the services namespace.
In the instances of a request such as GET service/v3/foo/bar both the service and the namespace do not exist. The kubectl command will fail with a 500 and we raise a CmdFailedError. We want to rescue this and actually return and empty string which we translate into a 404 for the requesting service.
We feel this is more accurate for what is actually happening. We only rescue the CmdFailedError so an actual 500 error will still respond correctly.
https://trello.com/c/XABkwrLb/1017-create-v3-service-token-cache-endpoint
Co-authored-by: Tomas Destefi <tomas.destefi@digital.justice.gov.uk>
Co-authored-by: Matt Tei …
=> Add V3 service endpoint

deploy/fb-service-token-cache-chart/templates/network_policy.yaml
This enables for applications in formbuilder-saas namespace to
make requests to the service token cache app
=> Add permission to formbuilder saas namespace

app/controllers/application_controller.rb, app/controllers/service_token_v2_controller.rb, app/controllers/service_token_v3_controller.rb, app/services/public_key_service.rb, spec/controllers/service_token_v2_controller_spec.rb, spec/controllers/service_token_v3_controller_spec.rb
We need to be able to cater for rotating the public keys. The service token cache has the `IGNORE_CACHE` environment variable which we could set to 'true' and then deploy the app out. However that would mean that every request received for every app would hit Kubernetes.
Passing an `ignore_cache` query parameter allows us to be more flexible when requesting the public key from Kubernetes. We only need to do so for the specific app that needs it instead of all of them at the same time
https://trello.com/c/zz1K8m9d/1039-add-ability-to-rotate-public-keys-in-the-api-without-downtime
=> Cater for ignore_cache query param

app/controllers/service_token_v3_controller.rb, app/services/adapters/kubectl_adapter.rb, app/services/support/service_token_authoritative_source.rb, config/routes.rb, spec/controllers/service_token_v3_controller_spec.rb, spec/services/adapters/kubectl_adapter_spec.rb
The same property is referenced across the platform using several different things but it always represents the same thing.
Eventually the actual thing that the request to the service token cache is trying to retrieve is the public key from Kubernetes or from the Redis if it has already been cached there.
The service slug is a parameterized version of the service name. But with version 3 of the service token cache endpoint the service_slug could also be related to a platform app, not just a form.
In Redis the key which is used takes the form:
`encoded-public-key-<service_slug>`
e.g `encoded-public-key-apply-financial-deputy`
And then if the cache has expired then the request to Kubernetes will look for a config map, _not_ a secret, which takes the form:
`fb-<service_slug>-config-map`
e.g …
=> Use service_slug for consistency

Gemfile.lock
Version 0.3.5 was yanked
https://rubygems.org/gems/mimemagic/versions/0.3.5
=> Bump mime magic

Gemfile, Gemfile.lock, app/services/adapters/kubectl_adapter.rb, config/initializers/sentry.rb
This adds the new sentry rails and ruby gems.
Configure the cleaning of the sensitive parameters.
Also enable performance monitoring for the upcoming trial.
=> Migrate to use new Sentry gem

deploy/fb-service-token-cache-chart/templates/deployment.yaml
We are continuing to investigate networking issues across our apps
inside the Cloud Platform infrastructure. One suggestion is to increase
the initialDelaySeconds to 15 seconds which we have previously done on
the datastore app.
=> Increase initialDelaySeconds

deploy/fb-service-token-cache-chart/templates/deployment.yaml
maxSurge: 100% means that 100% of the number of new replicas is allowed
to be created over the total number of replicas set.
In other words despite the config saying only 2 replicas can exist at
at any one time, during rollout a further 2 are allowed to exist at the
same time.
maxUnavailable: 50% means that at least 50% of the new replicas must be
available before scaling down of the old ones commences
=> Add rollout strategy to kubernetes config

Dockerfile
Cloud Platform uses version 1.18.2
https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/kops/live-1.yaml#L254
=> Use kubectl 1.18.2

.circleci/config.yml, app/controllers/health_controller.rb, config/routes.rb, deploy-eks/fb-service-token-cache-chart/templates/deployment.yaml, deploy-eks/fb-service-token-cache-chart/templates/hpa.yaml, deploy/fb-service-token-cache-chart/templates/deployment.yaml, deploy/fb-service-token-cache-chart/templates/hpa.yaml
This will check that there is an active connection to Redis before
allowing any traffic to be routed to a new container
This adds the ability for horizontal autoscaling to be done in both the
old cluster and the EKS cluster on a per namespace basis.
These can now be set individually per namespace using the
fb-service-token-cache-deploy repo
Parallelise the deployments to the dev and production namespaces in both
Test and Live.
=> Add horizontal autoscaling configuration

.circleci/config.yml
CircleCI will keep the Docker executor up to date on a rolling basis.
[CircleCi run](https://app.circleci.com/pipelines/github/ministryofjustice/fb-service-token-cache/1043/workflows/72573848-60a9-4c84-9bc9-f21793f70ef1)
=> Unpin Docker version in CircleCI pipeline

.circleci/config.yml
We have updated:
- deploy key for cloning the fb-service-token-cache-deploy repo
- moved environment variables to live in shared contexts and therefore udpated the pipeline jobs to use those
Co-authored-by: Natalie Seeto <natalie.seeto@digital.justice.gov.uk>
Co-authored-by: Steven Leighton <steven.leighton@digital.justice.gov.uk>
=> Update deployment config to use all the new settings
